### ISSUE TITLE
torch 2.0 support

### ISSUE THREAD

**Issue by colobas** [ryanirl/torchvf#1]
Hi! Apologies for the really naive question/request, but your package is a dependency of another package I depend on - do you plan on supporting torch 2.0? Per their release notes it's backwards compatible, so I don't think it should break anything.

**Comment by ryanirl** [comment]
Hi, thanks for bringing this to my attention. Not a naive question/request at all. I'm assuming this other package of yours is Omnipose. If you try and install either Omnipose or TorchVF with PyTorch 2.0 do you run into an error? 

Given PyTorch 2.0's backwards compatibility I will update the poetry dependencies to allow for any version of PyTorch greater than 1.6.0. Give me until tomorrow to get this updated.

**Comment by colobas** [comment]
No rush. In the meantime I did that in a fork, I'll open the PR

**Comment by ryanirl** [comment]
The PR would not be enough, I need to update the Poetry dependencies on my end for PyPI. Which I am having a bit of trouble with. Might be a couple of days.

**Comment by colobas** [comment]
Not sure I understand, but I'm happy to help with that.
Ping me at guilherme (dot) pires @ alleninstitute.org

**Comment by ryanirl** [comment]
Updating the dependencies through the GitHub repo would effect downloads if someone were to install via `pip install git+https://github.com/ryanirl/torchvf.git`. To update the wheel and make sure updates are reflected in PyPI (for example if someone were to install via `pip install torchvf`) I need to do some work on my end, and for some reason Poetry was giving me some issues when trying to publish the changes to PyPI.

**Comment by colobas** [comment]
Does it help if I submit a draft PR with a Github Action that handles publishing to PyPI?

**Comment by colobas** [comment]
I submitted a PR with a Github Action to push to PyPI on merges to `main`.
I tested it in my fork (see run [here](https://github.com/colobas/torchvf/actions/runs/4569195355/jobs/8065156171)), and you can see the build step succeeds.

(It fails at the publish step obviously, because I don't have your PyPI credentials - you'd have to setup the appropriate token as a repo secret called `PYPI_TOKEN`)

**Comment by ryanirl** [comment]
Thanks for the help. But again, the Poetry update is something that had to be done from my end not through GitHub. I figured out the problem (had to increment TorchVF version number) and it should work now. Don't forget to upgrade it (`pip install --upgrade torchvf`) if you already have it installed.
